### ISSUE TITLE
Can not resolve reference: `Xamarin.Android.Support.v7.RecyclerView`, referenced by `Sharpnado.Presentation.Forms.Droid`. 

### ISSUE THREAD

**Issue by LeoJHarris** [roubachof/Sharpnado.Presentation.Forms#102]
**Platform (please complete the following information):**
 - OS: Android
 - Device: Galaxy Tab A
 - Sdk vervion: Android SDK 10
 - Xamarin.Forms: 4.5.0.356

**Describe the bug**
Appears to be a reference issue with this project with the RecyclerView in Xamarin.Android 4.5.0.356 which is using AndroidX.RecyclerView.Widget and not the Android.Support.V7.Widget it previously did and which your project is using. Updating Xamarin Forms would imagine fix it but Im not sure what the backward comptability will be like.

Following build error is occuring:

**Please add a NuGet package or assembly reference for `Xamarin.Android.Support.v7.RecyclerView`, or remove the reference to `Sharpnado.Presentation.Forms.Droid`.	SampleApp.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1808**

**Comment by roubachof** [comment]
mmmh yes I will ask david about this.

**Comment by Redth** [comment]
Our recommendation is to follow the pattern we used in Xamarin.Essentials
https://github.com/xamarin/Essentials/pull/1095/files

The idea is to pivot on your dependency of Android Support for Android 9.0 (MonoAndroid90) or lower, and to use AndroidX for MonoAndroid10.0 or higher.

**Comment by roubachof** [comment]
Shane said it should work thanks to the AndroidX migration process included in XF 4.5.
Maybe have a look at the XamarinTV sample. It uses Sharpnado lib and XF 4.5  with no issues:

https://github.com/xamarin/app-xamarintv

**Comment by roubachof** [comment]
According to this doc:
https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/platform/android/androidx-migration

maybe try targeting android api v29

**Comment by PureWeen** [comment]
@LeoJHarris if you add 

https://www.nuget.org/packages/Xamarin.Android.Support.v7.RecyclerView/
https://www.nuget.org/packages/Xamarin.Android.Support.v7.CardView/

To your platform head does that fix the error?

**Comment by PureWeen** [comment]
@Redth I recreated the bug here on the XamarinTV app

https://github.com/xamarin/app-xamarintv/tree/androidx_bug

It looks like you have to add the support libraries to the head project otherwise you get the exception referenced by this issue

https://github.com/xamarin/app-xamarintv/blob/androidx_bug/XamarinTV.Android/XamarinTV.Android.csproj#L76

**Comment by PureWeen** [comment]
Sharpnado depends on XF 3.4 which has a transitive dependency on Support V27.0.2 (https://www.nuget.org/packages/Xamarin.Forms/3.4.0.1039999) 

I'm thinking that might be related

**Comment by roubachof** [comment]
It’s the minimal XF version, it doesn’t have a strong dependency.
If the auto migration process swaps namespaces from support to androidx, it should work...

**Comment by PureWeen** [comment]
@roubachof so we think the issue here is that you need to add the proper support nuget references into your nuspec. 

When users upgrade to XF 4.5 then XF 4.5 is explicitly added into the project head. This means that none of the support libraries will come across transitively. It doesn't matter that your nuspec specifies XF 3.4. 

So build the nuspec as if none of the support libraries are coming from XF. Indicate all the dependencies that your library directly has otherwise you're just at the mercy of what the user specifies in the project head

I think you'll need to add these three packages
```
<PackageReference Include="Xamarin.Android.Support.Compat">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v7.CardView">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v7.RecyclerView">
      <Version>28.0.0.3</Version>
    </PackageReference>
```

AndroidX rewrites the namespaces after everything has been compiled. So Sharpnado needs to be able to find the support recycler view, compile, and then it's all processed

**Comment by PureWeen** [comment]
Why do you compile Sharpnado against XF 4.4/4.5 but specify 3.4 in the nuspec?

**Comment by roubachof** [comment]
@PureWeen I don't :) 
I only use latest XF version in my sample silly app! (the Xamarin-Forms-Practices repo), since I add the Sharpnado repo as a submodule in this repo, all projects must have the same XF version.
I use this process to easily develop and test the library.

BUT, when I compile the lib, I use this script:
https://github.com/roubachof/Sharpnado.Presentation.Forms/blob/master/make-packages.ps1
It will swap the current XF version with the minimum XF version supported.

**Comment by PureWeen** [comment]
Aw cool that makes way more sense!!

What are your thoughts on multi targeting your android bits?

So if the users are targeting MonoAndroid90 then leave support at 3.4 but if they are targeting MonoAndroid100 then set support to XF 4.5 and only reference AndroidX libraries on your side as well?

**Comment by PureWeen** [comment]
Actually @roubachof 

I think you could still keep support down at 3.4 but then still multi target your android head so that if it's compiled against MonoAndroid10.0 you specifically add the androidx libraries you need and only use those namespaces and then if it's compiled against MonoAndroid9.0 you can use support

I don't think you'll have to raise the minimum XF dependency

**Comment by roubachof** [comment]
For the multi targeting, it seems clean, but I am concerned by the following scenario:

The user is using Android 9, XF 3.5 and Sharpnado 1.4.
Now for some reason he changes the target framework to 10 (I guess because he is procrastinating away from real work: a classic).
Now Sharpnado will scream saying he needs to update to latest version of XF (it could also fail to scream with weird msbuild error: we all met this situation :).
But maybe the latest version of XF is not working for him.
I don't want to force the user to update to last XF if it's not a real prerequisite to my lib...

**Comment by roubachof** [comment]
@PureWeen ohoh it seems all cool with your last advice then!

**Comment by PureWeen** [comment]
@roubachof 🤞 

The devils always in the details so let me know how it works!! I'm also checking with the AndroidX folks to make sure I'm not missing anything here

If you get a PR/preview nuget together let me know and I can test it out as well

**Comment by roubachof** [comment]
Great, will try that!
Thank you for helping me with the Android migration process, I really appreciate :)

**Comment by LeoJHarris** [comment]
@PureWeen I shifted to CollectionView very soon after this issue, unfortunately unable to test. I think it will help other people though using this library.

**Comment by roubachof** [comment]
@PureWeen Could you test the v1.5 of sharpnado see if it works?

What I did:

##### Build

```
compile with XF version 3.4

if MonoAndroid = v10.0
    compile against AndroidX libs
else 
    compile against Support libs api28
```

#### Nuget package

```
dependency XF version is 3.4

if MonoAndroid = v10.0
   dependency => AndroidX libs
 
lib\MonoAndroid10.0\*
lib\MonoAndroid90\*
```



[Sharpnado.Presentation.Forms.1.5.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Presentation.Forms/files/4402279/Sharpnado.Presentation.Forms.1.5.0.nupkg.zip)

**Comment by roubachof** [comment]
Solved by version 1.5

**Comment by PureWeen** [comment]
Hey sorry @roubachof I just noticed your comment

I'm guessing you also tested your 1.5.0 package against older forms version?

for example if someone has the following setup

- Target Platform API 29
- XF 3.4.0.1008975
- Sharpnado 1.5.0

Does that all work successfully?

**Comment by Martin080793** [comment]
For me this doesn't work. I am on the latest Xamarin.Forms and Sharpnado nuget versions. If i target API 29 i still get the error.

**Comment by roubachof** [comment]
@Martin080793 need a repro then cause I can’t reproduce.

**Comment by Martin080793** [comment]
[SharpnadoTest.zip](https://github.com/roubachof/Sharpnado.Presentation.Forms/files/4449572/SharpnadoTest.zip)

**Comment by roubachof** [comment]
Should be fixed by v1.5.1

**Comment by roubachof** [comment]
@PureWeen yup tested it against this scenario as well. With 1.5.1, should be all fine (I hope :)
